"""Traces the Sir Robert McAlpine logo into separate vector parts for the preloader and header.

srm.com only serves the logo as raster (a white PNG and the 1999px og:image JPEG on red), so the og:image is
thresholded, every white glyph is found as a connected shape, and each one is traced with potrace. Output:
lib/logo.ts (the red box size plus one path per letter, grouped into "Sir", "Robert" and "McALPINE") and
public/brand/logo-*.svg (light and dark, transparent background). Run: python3 scripts/logo.py
"""
import json, re, subprocess, tempfile, os
import numpy as np
from PIL import Image
from scipy import ndimage

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
img = np.asarray(Image.open(os.path.join(ROOT, "_scrape/og.jpg")).convert("L"), dtype=np.float32)
H, W = img.shape
white = img > 160
labels, n = ndimage.label(white)
boxes = ndimage.find_objects(labels)
parts = []
for i, sl in enumerate(boxes):
    y0, y1, x0, x1 = sl[0].start, sl[0].stop, sl[1].start, sl[1].stop
    if (y1 - y0) * (x1 - x0) < 400: continue
    parts.append(dict(id=i + 1, x0=x0, x1=x1, y0=y0, y1=y1))

# The dot of the "i" is its own shape: merge it into the stem below it.
parts.sort(key=lambda p: (p["y0"] > 420, p["x0"]))
merged = []
for p in parts:
    host = next((q for q in merged if q["y0"] < 420 and p["y1"] < 420 and abs(q["x0"] - p["x0"]) < 30 and (p["y1"] <= q["y0"] + 5 or q["y1"] <= p["y0"] + 5)), None)
    if host:
        host["ids"].append(p["id"]); host["y0"] = min(host["y0"], p["y0"]); host["y1"] = max(host["y1"], p["y1"])
    else:
        merged.append({**p, "ids": [p["id"]]})

names_top = list("SirRobert")
names_bottom = list("McALPINE")
top = sorted([p for p in merged if p["y0"] < 420], key=lambda p: p["x0"])
bottom = sorted([p for p in merged if p["y0"] >= 420], key=lambda p: p["x0"])
assert len(top) == 9 and len(bottom) == 8, (len(top), len(bottom))

def trace(mask):
    with tempfile.TemporaryDirectory() as d:
        Image.fromarray(np.where(mask, 0, 255).astype(np.uint8)).save(f"{d}/a.bmp")
        subprocess.run(["potrace", f"{d}/a.bmp", "-s", "-o", f"{d}/a.svg", "--flat", "-a", "0.8", "-O", "0.4", "-u", "10"], check=True)
        svg = open(f"{d}/a.svg").read()
    # potrace writes the path inside translate(0,H) scale(0.1,-0.1): bake that into absolute coordinates.
    ds = re.findall(r'<path d="([^"]+)"', svg)
    return " ".join(ds)

def bake(d):
    # Convert potrace's relative/absolute path (units of 0.1px, y flipped) into plain pixel coordinates.
    tokens = re.findall(r"[a-zA-Z]|-?\d*\.?\d+", d)
    out, i, cmd = [], 0, None
    cx = cy = sx = sy = 0.0
    def pt(x, y): return (x / 10.0, H - y / 10.0)
    while i < len(tokens):
        t = tokens[i]
        if re.match(r"[a-zA-Z]", t): cmd = t; i += 1
        if cmd in "Mm":
            x, y = float(tokens[i]), float(tokens[i + 1]); i += 2
            if cmd == "m": x += cx; y += cy
            cx, cy = x, y; sx, sy = x, y
            px, py = pt(x, y); out.append(f"M{px:.1f} {py:.1f}"); cmd = "l" if cmd == "m" else "L"
        elif cmd in "Ll":
            x, y = float(tokens[i]), float(tokens[i + 1]); i += 2
            if cmd == "l": x += cx; y += cy
            cx, cy = x, y; px, py = pt(x, y); out.append(f"L{px:.1f} {py:.1f}")
        elif cmd in "Cc":
            v = [float(tokens[i + k]) for k in range(6)]; i += 6
            if cmd == "c": v = [v[0] + cx, v[1] + cy, v[2] + cx, v[3] + cy, v[4] + cx, v[5] + cy]
            a, b, c = pt(v[0], v[1]), pt(v[2], v[3]), pt(v[4], v[5]); cx, cy = v[4], v[5]
            out.append(f"C{a[0]:.1f} {a[1]:.1f} {b[0]:.1f} {b[1]:.1f} {c[0]:.1f} {c[1]:.1f}")
        elif cmd in "Zz":
            out.append("Z"); cx, cy = sx, sy
        else:
            raise ValueError(cmd)
    return "".join(out)

def path_for(p):
    mask = np.isin(labels, p["ids"])
    return bake(trace(mask))

# Red box: the og:image is the logo's own lock-up, so the whole frame is the box.
glyphs = []
for word, group in (("sir", top[:3]), ("robert", top[3:]), ("mcalpine", bottom)):
    pass
letters = [("sir", c, p) for c, p in zip("Sir", top[:3])] + [("robert", c, p) for c, p in zip("Robert", top[3:])] + [("mcalpine", c, p) for c, p in zip("McALPINE", bottom)]
for word, ch, p in letters:
    glyphs.append(dict(word=word, char=ch, d=path_for(p), box=[p["x0"], p["y0"], p["x1"], p["y1"]]))

ts = "// Generated by scripts/logo.py from srm.com's og:image (the only full-size copy of the logo). Do not edit.\n"
ts += f"export const LOGO_W = {W};\nexport const LOGO_H = {H};\n"
ts += "export type Glyph = { word: \"sir\" | \"robert\" | \"mcalpine\"; char: string; d: string };\n"
ts += "export const glyphs: Glyph[] = " + json.dumps([{k: g[k] for k in ("word", "char", "d")} for g in glyphs], indent=1) + ";\n"
open(os.path.join(ROOT, "lib/logo.ts"), "w").write(ts)

allpaths = "".join(f'<path d="{g["d"]}"/>' for g in glyphs)
for name, box, ink in (("logo-red", "#E4032C", "#FFFFFF"), ("logo-white", "none", "#FFFFFF"), ("logo-slate", "none", "#3A4953")):
    rect = f'<rect width="{W}" height="{H}" fill="{box}"/>' if box != "none" else ""
    svg = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {W} {H}">{rect}<g fill="{ink}">{allpaths}</g></svg>'
    open(os.path.join(ROOT, f"public/brand/{name}.svg"), "w").write(svg)
print("glyphs", len(glyphs), "size", W, H)
for g in glyphs: print(g["word"], g["char"], g["box"])

# Favicon: the "Mc" of the wordmark on the red box (the live favicons are a green and red Net Zero graphic).
mc = [g for g in glyphs if g["word"] == "mcalpine" and g["char"] in "Mc"]
x0 = min(g["box"][0] for g in mc); x1 = max(g["box"][2] for g in mc)
y0 = min(g["box"][1] for g in mc); y1 = max(g["box"][3] for g in mc)
side = max(x1 - x0, y1 - y0) * 1.36
cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
vb = f"{cx - side / 2:.0f} {cy - side / 2:.0f} {side:.0f} {side:.0f}"
icon = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb}"><rect x="{cx - side / 2:.0f}" y="{cy - side / 2:.0f}" width="{side:.0f}" height="{side:.0f}" fill="#E4032C"/><g fill="#FFFFFF">' + "".join(f'<path d="{g["d"]}"/>' for g in mc) + "</g></svg>"
open(os.path.join(ROOT, "app/icon.svg"), "w").write(icon)
